name: 'Invoke URI'
description: 'Call a URI and return the result'
author: foss@cuedo.com.au
branding:
  icon: 'link-2'
  color: 'orange'
inputs:
  uri:
    required: true
    description: "Invoke the specified URI"
  filename:
    description: "Save the output to the specified file"
  user-agent:
    description: "Custom user agent"
  max-redirections:
    description: "The maximum number of redirections"
    default: 5
  retries:
    description: "Retry the request if it fails"
    default: 3
runs:
  using: "composite"
  steps:
    - name: Invoke URI (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: export DISPLAY="127.0.0.1:10.0"
      
    - name: Invoke URI (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      env:
        URI: ${{ format('-Uri {0}', inputs.uri) }}
        FILENAME: ${{ inputs.filename != '' && format(' -OutFile "{0}"', inputs.filename) || '' }}
        USER_AGENT: ${{ inputs.user-agent != '' && format(' -UserAgent "{0}"', inputs.user-agent) || '' }}
        MAX_REDIRECTIONS: ${{ inputs.max-redirections != 5 && format(' -MaximumRedirection {0}', inputs.max-redirections) || '' }}
        RETRIES: ${{ inputs.retries != 3 && format(' -MaximumRetryCount {0}', inputs.retries) || '' }}
      run: |
        Invoke-WebRequest ${{env.URI}}${{env.FILENAME}}${{env.USER_AGENT}}${{env.MAX_REDIRECTIONS}}${{env.RETRIES}}
