name: 'Invoke URI'
description: 'Call a URI and return the result'
author: foss@cuedo.com.au
branding:
  icon: 'link-2'
  color: 'orange'
inputs:
  method:
    description: "Specifies the method used for the web request"
    default: "get"
  uri:
    required: true
    description: "Invoke the specified URI"
  content-type:
    description: "Set the content type of the request"
    default: 'application/json'
  filename:
    description: "Save the output to the specified file"
  user-agent:
    description: "Custom user agent"
  max-redirections:
    description: "The maximum number of redirections"
    default: 5
  retries:
    description: "Retry the request if it fails"
    default: 3
  retry-interval:
    description: "The retry interval in seconds"
    default: 5
  retry-timeout:
    description: "The time in seconds before each request will timeout and retry if possible"
    default: 60
runs:
  using: "composite"
  steps:
    - name: Invoke URI (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: export DISPLAY="127.0.0.1:10.0"
      
    - name: Invoke URI (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      env:
        METHOD: ${{ format(' -Method ''{0}''', inputs.method) }}
        URI: ${{ format(' -Uri ''{0}''', inputs.uri) }}
        CONTENT_TYPE: ${{ format(' -ContentType ''{0}''', inputs.content-type) }}
        FILENAME: ${{ inputs.filename != '' && format(' -PassThru -OutFile ''{0}''', inputs.filename) || '' }}
        USER_AGENT: ${{ inputs.user-agent != '' && format(' -UserAgent ''{0}''', inputs.user-agent) || '' }}
        MAX_REDIRECTIONS: ${{ inputs.max-redirections != 5 && format(' -MaximumRedirection {0}', inputs.max-redirections) || '' }}
        RETRIES: ${{ inputs.retries != 3 && format(' -MaximumRetryCount {0}', inputs.retries) || '' }}
        RETRY_INTERVAL: ${{ inputs.retry-interval != 5 && format(' -RetryIntervalSec {0}', inputs.retry-interval) || '' }}
        RETRY_TIMEOUT: ${{ inputs.retry-timeout != 5 && format(' -TimeoutSec {0}', inputs.retry-timeout) || '' }}
      run: |
        Invoke-WebRequest ${{env.METHOD}}${{env.URI}}${{env.CONTENT_TYPE}}${{env.FILENAME}}${{env.USER_AGENT}}${{env.MAX_REDIRECTIONS}}${{env.RETRIES}}${{env.RETRY_INTERVAL}}${{env.RETRY_TIMEOUT}}
