on: [push]
name: test-ubuntu-latest
jobs:
  test-action:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          uri: https://google.com/
          filename: google.html
          user-agent: "Cuedo"
          max-redirections: 11
          retries: 3
